---
loopback_interface: Loopback0
loopback_ip: 10.1.1.1/32

interfaces:
  - name: Ethernet0/0
    ip: 10.1.12.1/24
    description: Link to R2

ospf:
  process_id: 1
  router_id: 10.1.1.1
  networks:
    - "network 10.1.12.0 0.0.0.255 area 0"
    - "network 10.1.1.1 0.0.0.0 area 0"
