---
loopback_interface: lo0
loopback_ip: 10.1.3.3/32

interfaces:
  - name: ge-0/0/2
    ip: 10.1.23.3/24
    description: Link to R2

ospf:
  area: "0.0.0.0"
  interfaces:
    - "ge-0/0/2.0"
    - "lo0.0"
