---
loopback_interface: Loopback0
loopback_ip: 10.1.2.2/32

interfaces:
  - name: Ethernet1
    ip: 10.1.12.2/24
    description: Link to R1
  - name: Ethernet2
    ip: 10.1.23.2/24
    description: Link to R3

ospf:
  process_id: 1
  router_id: 10.1.2.2
  networks:
    - "network 10.1.12.0 0.0.0.255 area 0"
    - "network 10.1.23.0 0.0.0.255 area 0"
    - "network 10.1.2.2 0.0.0.0 area 0"
